FROM openjdk:17-jdk-slim

# 1. ocrmypdf 설치
RUN apt-get update && \
    apt-get install -y \
    ocrmypdf \
    tesseract-ocr-kor

# 2. 빌드 파일 복사 후 실행
WORKDIR /app
COPY server/build/install/server/ /app
EXPOSE 8081
CMD ["./bin/server", "-allow", "$ALLOW_HOST"]